default:
  outputs:
    local:
      type: spark
      method: session
      schema: 'default'
      host: NA
      server_side_parameters:
        'spark.log.level': 'ERROR'
        'spark.jars.packages': 'io.delta:delta-spark_2.12:3.1.0'
        'spark.sql.extensions': 'io.delta.sql.DeltaSparkSessionExtension'
        'spark.sql.catalog.spark_catalog': 'org.apache.spark.sql.delta.catalog.DeltaCatalog'
